### ISSUE TITLE
[BUG] Unsupported ZIP compression method in an ODT escapes as NotImplementedError

### ISSUE THREAD

**Issue by DrVelvetFog** [maziyarpanahi/openmed#3298]
## Bug description

`extract_odt` documents that it raises `UnsupportedDocumentError` when the archive is
"missing, encrypted, mislabeled, or malformed". Its guard catches
`(OSError, zipfile.BadZipFile, zlib.error)`.

An ODT whose `content.xml` declares a compression method the runtime does not implement is
malformed, but `zipfile._check_compression` raises `NotImplementedError`, which is not in
that tuple. It escapes `_read_required` (`openmed/multimodal/odt.py:364`) and leaves the
handler, so a caller that correctly handles `UnsupportedDocumentError` still crashes.

This is one of the parser failures you asked me to file separately from #3242. The nightly
Fuzz job hit it on 2026-09-04, run 33850974038.

Note the neighbouring case is already handled: a corrupted deflate stream in the same
position raises `zlib.error`, which the tuple does catch, and comes back as
`UnsupportedDocumentError`. Only the unsupported-method path is unguarded.

## Minimal reproduction

The script below builds a valid ODT and changes exactly one field — `content.xml`'s
compression method, in both the local header and the central directory. Everything else is
a well-formed archive, and the same script without those two writes parses cleanly.

```python
import io, struct, zipfile, tempfile, pathlib
from openmed.multimodal.odt import _odt_handler

XML = (b'<?xml version="1.0" encoding="UTF-8"?>'
       b'<office:document-content'
       b' xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"'
       b' xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0">'
       b'<office:body><office:text><text:p>Synthetic note for PATIENT-001.</text:p>'
       b'</office:text></office:body></office:document-content>')

buf = io.BytesIO()
with zipfile.ZipFile(buf, "w") as z:
    z.writestr("mimetype", "application/vnd.oasis.opendocument.text",
               compress_type=zipfile.ZIP_STORED)
    z.writestr("content.xml", XML, compress_type=zipfile.ZIP_DEFLATED)
raw = bytearray(buf.getvalue())

struct.pack_into("<H", raw, raw.find(b"content.xml") - 26 + 8, 99)
cd = raw.rfind(b"PK\x01\x02")
while cd != -1:
    if raw[cd + 46:cd + 57] == b"content.xml":
        struct.pack_into("<H", raw, cd + 10, 99)
        break
    cd = raw.rfind(b"PK\x01\x02", 0, cd)

with tempfile.TemporaryDirectory() as d:
    p = pathlib.Path(d) / "synthetic.odt"
    p.write_bytes(bytes(raw))
    _odt_handler(p, policy=None, models=lambda t, **_: t, lang="en")
```

## Expected behavior

`UnsupportedDocumentError`, as the docstring promises for a malformed archive. Adding
`NotImplementedError` to the existing tuple at `openmed/multimodal/odt.py:337` covers it,
and also covers `_ensure_supported_archive`'s `archive.read("mimetype")` on the same path.

## Error output

```
  File "openmed/multimodal/odt.py", line 364, in _read_required
    return archive.read(path)
  File ".../zipfile/__init__.py", line 851, in _check_compression
    raise NotImplementedError("That compression method is not supported")
NotImplementedError: That compression method is not supported
```

## OpenMed version

2.5.0 (master `b161a18f5`)

## Operating system

macOS 26.6.2 (arm64)

## Python version

3.14.6. The CI failure was on 3.11.16; the path is not version-specific.

## Model ID

Not applicable — parser level, no model is loaded (`models` is an identity stub).

## Additional context

Happy to open the PR for this one if you want it.

## Privacy confirmation

- [x] I confirm that this issue contains no PHI, PII, secrets, or real patient data. The
      fixture is generated by the script above and contains one synthetic token.

**Comment by maziyarpanahi** [comment]
Thanks @DrVelvetFog — this failure already has an open implementation in #3261 for #3246. It adds an explicit supported-compression gate before either ODT read site, so please put your unsupported-method fixture on #3261 rather than open a duplicate fix. Keep the fixture synthetic and verify the documented UnsupportedDocumentError outcome, including unsupported compression on mimetype as well as content.xml. I’m leaving this report unassigned while that work is active.

**Comment by DrVelvetFog** [comment]
Closing this as fixed. #3261 landed this morning and closed #3246, which turns out to be my own earlier report of the same bug. I filed this one without checking my own history, sorry for the noise.

I re-ran the repro above on master `935fcc072` and it now comes back as `UnsupportedDocumentError` from the archive gate.
